### ISSUE TITLE
Potential headaches

### ISSUE THREAD

**Issue by lnay** [glams-lean-2024/formal-2024#6]
Just documenting a thought here.

I don't know how lean works or what olean files are, but a potential red flag is that `.lake` contains a compressed folder [linux-64.tar.gz](https://github.com/glams-lean-2024/formal-2024/blob/main/.lake/linux-64.tar.gz) which I'm assuming was uncompressed to make up some of the contents of `.lake`.

Given the name, this stuff is almost certainly platform specific. Alvaro was also having some issue on mac (@PatrickKinnear  saw more of that), potentially related. The other thing to note was that `.lake` was not included in the original repo (and was gitignored).

Although since this 'works' or can be worked around, this could just be ignored if this repo is only being used in the first weeks (where people would use codespaces anyway).

**Comment by themathqueen** [comment]
yeah, I see what you mean. It works well in Codespaces and Gitpod, but doesn't work so well locally

**Comment by AdrianDoM** [comment]
Do we need the `.lake` directory for the Codespaces to work?

**Comment by lnay** [comment]
There was mention of things not working on codespaces at some point (Adrian and Patrick?). I haven't experienced that, I don't know what the issue was and if it's related. One possible think to keep in mind is that the codespaces runs a couple of lake commands after the VSCode window opens (but not immediately obvious). So Lean isn't usable on the project for a delay. Preinstalling mathlib (if worked out how), could make sense in a prebuilt devcontainer, but I think doing it in the repo instead has risks.

To be clear, I'm not advocating for possibly breaking changes the day before the next workshop. This was fine last time, just to keep in mind with attendee issues.

**Comment by AdrianDoM** [comment]
I just checked in a new branch and that the `.lake` dir is not needed for the Codespaces to work. When people move to a local copy of the repo they won't want to have the `.lake` included, because it will be system dependent. However, as Luke has pointed out to me, since `.lake` is already tracked by git, it won't just happily forget about it. When pulling a version without a `.lake` it will probably delete the local one. This is fine as long as one runs `lake exe cache get` after pulling, to build a local version of the `.lake` directory.
